export const folderStructure = [
    '+Inbox',
    'Archive/Backup',
    'Archive/Social Media',
    'Archive/Web',
    'Audio/Books',
    'Audio/Music/Various Artists',
    'Audio/Playlists',
    'Audio/Podcasts',
    'Document/Important',
    'Document/Recipes',
    'Document/Scans/Receipts',
    'Image/Artwork',
    'Image/Charts',
    'Image/Memes',
    'Image/Photos',
    'Image/Screenshots',
    'Image/Sketches',
    'Image/Wallpapers',
    'Image/Web',
    'Notes',
    'School',
    'Software/Applications',
    'Software/Assets/2D',
    'Software/Assets/3D',
    'Software/Assets/Concepts',
    'Software/Assets/Drawings',
    'Software/Assets/Icons',
    'Software/Assets/Materials',
    'Software/Assets/SoundFX',
    'Software/Assets/Typefaces',
    'Software/Coding/Libraries',
    'Software/Coding/Plugins',
    'Software/Coding/Projects',
    'Software/Coding/Scripts',
    'Software/Coding/Sources',
    'Software/Configs',
    'Software/Games',
    'Software/Tutorials',
    'Video/Movies',
    'Video/Shows',
    'Video/Web/YouTube',
    'Writing/0 Science. Knowledge./Newspapers. Magazines. Journals',
    'Writing/1 Philosophy. Psychology',
    'Writing/2 Religion. Theology',
    'Writing/3 Social sciences/Customs. Etiquette',
    'Writing/3 Social sciences/Economics',
    'Writing/3 Social sciences/Education',
    'Writing/3 Social sciences/Law',
    'Writing/3 Social sciences/Politics',
    'Writing/4 Currently Vacant',
    'Writing/5 Mathematics. Natural sciences/Biology',
    'Writing/5 Mathematics. Natural sciences/Botany',
    'Writing/5 Mathematics. Natural sciences/Chemistry',
    'Writing/5 Mathematics. Natural sciences/Mathematics',
    'Writing/5 Mathematics. Natural sciences/Physics',
    'Writing/5 Mathematics. Natural sciences/Zoology',
    'Writing/6 Technology. Medicine. Applied Sciences./Computer science/Algorithms',
    'Writing/6 Technology. Medicine. Applied Sciences./Computer science/Artificial Intelligence',
    'Writing/6 Technology. Medicine. Applied Sciences./Computer science/Computer',
    'Writing/6 Technology. Medicine. Applied Sciences./Computer science/Data',
    'Writing/6 Technology. Medicine. Applied Sciences./Computer science/Hardware',
    'Writing/6 Technology. Medicine. Applied Sciences./Computer science/Internet',
    'Writing/6 Technology. Medicine. Applied Sciences./Computer science/Security',
    'Writing/6 Technology. Medicine. Applied Sciences./Computer science/Software',
    'Writing/6 Technology. Medicine. Applied Sciences./Engineering',
    'Writing/6 Technology. Medicine. Applied Sciences./Medicine',
    'Writing/6 Technology. Medicine. Applied Sciences./Technology',
    'Writing/7 Arts. Recreation. Entertainment. Sport./Architecture',
    'Writing/7 Arts. Recreation. Entertainment. Sport./Drawing',
    'Writing/7 Arts. Recreation. Entertainment. Sport./Graphic design',
    'Writing/7 Arts. Recreation. Entertainment. Sport./Music',
    'Writing/7 Arts. Recreation. Entertainment. Sport./Painting',
    'Writing/7 Arts. Recreation. Entertainment. Sport./Photography',
    'Writing/8 Language. Linguistics. Literature/Linguistics and languages',
    'Writing/8 Language. Linguistics. Literature/Literature/Drama. Plays',
    'Writing/8 Language. Linguistics. Literature/Literature/Essays. Speeches',
    'Writing/8 Language. Linguistics. Literature/Literature/Fiction. Novels',
    'Writing/8 Language. Linguistics. Literature/Literature/Poetry. Verses',
    'Writing/9 Geography. Biography. History/Biography',
    'Writing/9 Geography. Biography. History/Geography',
    'Writing/9 Geography. Biography. History/History/Ancient History',
    'Writing/9 Geography. Biography. History/History/Medieval History',
    'Writing/9 Geography. Biography. History/History/Modern History',
    'Writing/9 Geography. Biography. History/History/World History',
];
